// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"firemap/internal/application/service"
	"firemap/internal/application/usecase"
	"firemap/internal/infrastructure/chat"
	"firemap/internal/infrastructure/config"
	"firemap/internal/infrastructure/db"
	"firemap/internal/infrastructure/repository"
	"firemap/internal/infrastructure/server"
	"firemap/internal/infrastructure/server/handlers"
	"firemap/internal/infrastructure/translator"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeProcessManager() *ProcessManager {
	configConfig := config.LoadFromEnvironment()
	sqlDB := db.NewDBForMigrations(configConfig)
	gormDB := db.NewDB(configConfig)
	userRepository := repository.NewUserRepository(gormDB)
	userService := service.NewUserService(userRepository)
	userAuthenticator := usecase.NewUserAuthenticator(userService)
	login := handlers.NewLogin(userAuthenticator)
	userRegistrator := usecase.NewUserRegistrator(userService)
	register := handlers.NewRegister(userRegistrator)
	userGetter := usecase.NewUserGetter(userService)
	authMe := handlers.NewAuthMe(userGetter)
	markerRepository := repository.NewMarkerRepository(gormDB)
	markerService := service.NewMarkerService(markerRepository)
	reportRepository := repository.NewReportRepository(gormDB)
	reportService := service.NewReportService(reportRepository)
	chatRepository := repository.NewChatRepository(gormDB)
	messageRepository := repository.NewMessagesRepository(gormDB)
	chatService := service.NewChatService(chatRepository, messageRepository)
	chatUserRepository := repository.NewChatUserRepository(gormDB)
	chatUserService := service.NewChatUserService(chatUserRepository)
	markerCreator := usecase.NewMarkerCreator(userService, markerService, reportService, chatService, chatUserService)
	createMarker := handlers.NewCreateMarker(markerCreator)
	markerGetter := usecase.NewMarkersGetter(userService, markerService)
	getMarkers := handlers.NewGetMarkers(markerGetter)
	chatHistoryGetter := usecase.NewChatHistoryGetter(userService, markerService, chatService)
	getChatHistory := handlers.NewGetChatHistory(chatHistoryGetter)
	hub := chat.NewHub(messageRepository, userRepository, chatRepository)
	sendMessage := handlers.NewSendMessage(hub)
	chatConnector := usecase.NewChatConnector(userService, chatService, markerService, chatUserService)
	connectToChat := handlers.NewConnectToChat(chatConnector)
	translatorTranslator := translator.NewClient(configConfig)
	translateMessage := handlers.NewTranslateMessage(messageRepository, translatorTranslator)
	chatGetter := usecase.NewChatGetter(userService, markerService, chatService)
	getAllChats := handlers.NewGetAllChats(chatGetter)
	v := server.NewRoutes(login, register, authMe, createMarker, getMarkers, getChatHistory, sendMessage, connectToChat, translateMessage, getAllChats)
	processManager := NewProcessManager(configConfig, sqlDB, v, hub)
	return processManager
}

// wire.go:

var chatSet = wire.NewSet(chat.NewHub)
