// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"firemap/internal/application/service"
	"firemap/internal/application/usecase"
	"firemap/internal/infrastructure/config"
	"firemap/internal/infrastructure/db"
	"firemap/internal/infrastructure/repository"
	"firemap/internal/infrastructure/server"
	"firemap/internal/infrastructure/server/handlers"
)

// Injectors from wire.go:

func InitializeProcessManager() *ProcessManager {
	configConfig := config.LoadFromEnvironment()
	sqlDB := db.NewDBForMigrations(configConfig)
	gormDB := db.NewDB(configConfig)
	userRepository := repository.NewUserRepository(gormDB)
	userService := service.NewUserService(userRepository)
	userAuthenticator := usecase.NewUserAuthenticator(userService)
	auth := handlers.NewAuth(userAuthenticator)
	userRegistrator := usecase.NewUserRegistrator(userService)
	signup := handlers.NewASignup(userRegistrator)
	v := server.NewRoutes(auth, signup)
	processManager := NewProcessManager(configConfig, sqlDB, v)
	return processManager
}
