// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"firemap/internal/application/service"
	"firemap/internal/application/usecase"
	"firemap/internal/infrastructure/config"
	"firemap/internal/infrastructure/db"
	"firemap/internal/infrastructure/repository"
	"firemap/internal/infrastructure/server"
	"firemap/internal/infrastructure/server/handlers"
)

// Injectors from wire.go:

func InitializeProcessManager() *ProcessManager {
	configConfig := config.LoadFromEnvironment()
	sqlDB := db.NewDBForMigrations(configConfig)
	gormDB := db.NewDB(configConfig)
	userRepository := repository.NewUserRepository(gormDB)
	userService := service.NewUserService(userRepository)
	userAuthenticator := usecase.NewUserAuthenticator(userService)
	login := handlers.NewLogin(userAuthenticator)
	userRegistrator := usecase.NewUserRegistrator(userService)
	register := handlers.NewRegister(userRegistrator)
	userGetter := usecase.NewUserGetter(userService)
	authMe := handlers.NewAuthMe(userGetter)
	markerRepository := repository.NewMarkerRepository(gormDB)
	markerService := service.NewMarkerService(markerRepository)
	reportRepository := repository.NewReportRepository(gormDB)
	reportService := service.NewReportService(reportRepository)
	chatRepository := repository.NewChatRepository(gormDB)
	chatService := service.NewChatService(chatRepository)
	markerCreator := usecase.NewMarkerCreator(userService, markerService, reportService, chatService)
	createMarker := handlers.NewCreateMarker(markerCreator)
	v := server.NewRoutes(login, register, authMe, createMarker)
	processManager := NewProcessManager(configConfig, sqlDB, v)
	return processManager
}
